# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findafountain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='fountain_images')),
                ('description', models.CharField(max_length=250)),
                ('floor', models.IntegerField(default=0)),
                ('reviews', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('numberratings', models.IntegerField(default=0)),
                ('avgrating', models.FloatField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('broken', models.BooleanField(default='false')),
            ],
        ),
    ]
